version: "3"
services:
  gamestore-database:
    image: postgres
    container_name: gamestore-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=gamestore
      - POSTGRES_DB=gamestoredb
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local